### PR TITLE
Added support for 'switch' statements

### PR DESCRIPTION
**Pull request by evolutional**
Added support for 'switch' statements with C/C++-like fall-through to the next compound statement.

Supporting syntax such as:
```
a = 10;
switch(a)
{
  case 0: { print("a = 0"); }
  case 1:
  case 2:
  case 3:
  case 4:
  case 5: { print("a is a number between 1 and 5");  }
  case "test": { print("a is a string with a value of 'test'"); }
  default: { print("not handled by case"); }
};
```
Unlike C/C++ ```break``` isn't supported/required; the first  (brace delineated) compound statement is executed during the fall-through process.

Brought up to date from the original implementation in 2009 - http://www.gmscript.com/gamemonkey/forum/viewtopic.php?f=14&t=445#p2214

### CODE REVIEW

**Comment by evolutional** [comment]
Depends what you want to do with this - whether an experimental / vNext branch is preferred or not. I originally added this code in 2009 and maintained it in my private forks / projects. Felt it might be useful. From memory it was faster than equivalent if/else if/else if type code due to the single evaluation of the selection expression.

**Comment by publicrepo** [comment]
My attitude at present is that GM benefits from *more* C compatible syntax. Basically it's what most users know and expect. I think it was wrong to try and diverge from C so much and remove some of the basic operators etc.
So I'm happy to put switch in, as long as you or I can verify stability and quality of the code.

**Comment by evolutional** [comment]
I agree. Way back when I tried getting this to support C-like switch statements but ended up with yacc shift/reduce errors, I guess the grammar was ambiguous - as I said, this was stuff I was using 9 years ago :)

I'll have a look with fresh eyes to see if I can wrangle it into something we know and love.

On the subject of fresh eyes and testing, I don't know how you used to verify the code when iterating on it and taking changes from the community. These days we'd have automated unit/integration tests - perhaps something similar would be valid here?

**Comment by publicrepo** [comment]
RE switch, I think the closer to C the better, but people would still be happier to have switch than not. Certainly have another go if you have time.

Speaking of time, if you do have some to spare (and desire to improve GM), I have a couple of suggested things to attempt.  I don't expect to do more than critical bug fixing in the near term myself.

Verification used to look like eye balling code and running all scripts I had access to. For code gen, I also compared annotated byte code from the lib tool.  Most features and bug fixes were straight forward and of limited scope. A set of test scripts with comparable output would be better for regression testing.

**Pull request merged**
